apiVersion: v2
name: platform-addons
description: Umbrella Helm chart for Cluckin Bell platform add-ons
type: application
version: 0.2.0
appVersion: "1.0.0"

# Dependencies
dependencies:
  - name: aws-load-balancer-controller
    version: "1.7.2"
    repository: "https://aws.github.io/eks-charts"
    condition: platformAddons.awsLoadBalancerController.enabled
  - name: external-dns
    version: "1.14.5"
    repository: "https://kubernetes-sigs.github.io/external-dns/"
    condition: platformAddons.externalDNS.enabled
  - name: cert-manager
    version: "v1.15.3"
    repository: "https://charts.jetstack.io"
    condition: platformAddons.certManager.enabled
  - name: metrics-server
    version: "3.12.2"
    repository: "https://kubernetes-sigs.github.io/metrics-server/"
    condition: platformAddons.metricsServer.enabled
  - name: kube-prometheus-stack
    version: "62.6.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: platformAddons.kubePrometheusStack.enabled
