apiVersion: v2
name: karpenter
description: Karpenter Helm chart with NodePool and EC2NodeClass configurations
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: karpenter
    version: "1.0.8"
    repository: "oci://public.ecr.aws/karpenter"
    condition: karpenter.enabled
